#,-.----.
#\    /  \                                           ,----..      ,---,.
#|   :    \   ,--,                                  /   /   \   ,'  .' |
#|   |  .\ :,--.'|                                 |   :     :,---.'   |
#.   :  |: ||  |,     ,----._,.  ,----._,.         .   |  ;. /|   |   .'
#|   |   \ :`--'_    /   /  ' / /   /  ' /     .--,.   ; /--` :   :  |-,
#|   : .   /,' ,'|  |   :     ||   :     |   /_ ./|;   | ;    :   |  ;/|
#;   | |`-' '  | |  |   | .\  .|   | .\  ., ' , ' :|   : |    |   :   .'
#|   | ;    |  | :  .   ; ';  |.   ; ';  /___/ \: |.   | '___ |   |  |-,
#:   ' |    '  : |__'   .   . |'   .   . |.  \  ' |'   ; : .'|'   :  ;/|
#:   : :    |  | '.'|`---`-'| | `---`-'| | \  ;   :'   | '/  :|   |    \
#|   | :    ;  :    ;.'__/\_: | .'__/\_: |  \  \  ;|   :    / |   :   .'
#`---'.|    |  ,   / |   :    : |   :    :   :  \  \\   \ .'  |   | ,'
#  `---`     ---`-'   \   \  /   \   \  /     \  ' ; `---`    `----'
#                      `--`-'     `--`-'       `--`

# Enchant Rarity Color
# List of available colors:
# black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, and white.
color:
  common: yellow
  uncommon: blue
  rare: gold
  mythical: light_purple
# Leave empty to allow JetPack anywhere, or add worlds where JetPack is disabled: ["PvPArena", "AnotherWorld"]
jetpack:
  disabled: []